apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=https://vadim-platform.ngrok.io
  - cors=https://vadim-platform.ngrok.io
  - env=production
  name: cap-app-proxy-cm
kind: Kustomization
namespace: mycsdptest
resources:
- ../../base
- ingress.yaml
